import { Geist, Geist_Mono } from "next/font/google";
import "./global.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import GlobalProvider from "@/components/globalState/GlobalProvider";
import { ToastContainer } from "react-toastify";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Keen Keeper",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      data-theme='light'
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="bg-primary-bg min-h-screen">

        <header className="fixed w-full top-0 shadow-sm bg-white z-20">
          <Navbar />
        </header>

        <GlobalProvider>
          {children}
        </GlobalProvider>

        <Footer />
        <ToastContainer position="top-center" autoClose={2000} />
      </body>
    </html>
  );
}
